### ISSUE TITLE
Warning: Failed context type: The context `stripe` is marked as required in `Elements`, but its value is `undefined`.

### ISSUE THREAD

**Issue by yasharma** [stripe/react-stripe-elements#110]
I've working on signup form which has 3 steps signup form and i am using `redux-form` wizard form, after submit first form it throws error:
```javascript
Warning: Failed context type: The context `stripe` is marked as required in `Elements`, but its value is `undefined`.
Uncaught TypeError: Cannot read property 'elements' of undefined
```
Help needed with this issue, here is my code repo (https://github.com/yasharma/socialapp/tree/develop/src/components)
1. Main Component `Register.js`  
2. Step 1 `AccountSetUp.js`  
3. Step 2 `Subscription.js`  
4. Step 3 `Confirm Payment`  

As soon as code reached step 3 it throws error. I am using individual `Element*` to create my stripe form and then on form submit it called `stripe.createToken()`,

Need assistance and guidance on this

**Comment by cweiss-stripe** [comment]
Thanks for reporting this and for the provided example!

I think due to the way reduxForm uses `shouldComponentUpdate` and does not take context changes into account.
To prevent this issue you can try to add the [`pure: false`](https://redux-form.com/7.1.1/docs/api/reduxform.md/#-code-pure-boolean-code-optional-) option to your [`reduxForm()` call](https://github.com/yasharma/socialapp/blob/e0053c1c8c77acea944ac19921913c4fba6d76a2/src/components/ConfirmPayment.js#L91).
Also see  https://github.com/stripe/react-stripe-elements#troubleshooting for more details on that issue.

Please let me know if that fixes your issue!

**Comment by yasharma** [comment]
Thanks @cweiss-stripe for correct reference, However even with `pure: false` problem is still there, sometimes when comes from another routes it throws error but sometimes not, i mean this is not complete solution, initially i think its fixed but i saw same error in console during development other things, when moves to that page but not every time. so what i think and i even test this with normal form without redux form, its working fine so i am going with that solution, until found something solid.
