### ISSUE TITLE
Use Stripe CardElement to display existing card information

### ISSUE THREAD

**Issue by mitchswaldman** [stripe/react-stripe-elements#126]
Is there a way to use the CardElement to display existing card information rather than using it purely as an input field? Something to this effect...

```
class SomeComponent extends React.Component {
  render() {
    const cardDetails = {
        last4 : 1234,
        brand : 'Visa',
        name : 'John Smith'
    }
    return (
      <CardElement details={cardDetails} />
    )
  }
}
```

**Comment by jez** [comment]
Hey @mitchswaldman! This is a really cool idea! Unfortunately, it's not something that's implemented right now, mostly by design. If users were to have control over the actual data inside an element, there'd be a greater chance they accidentally put themselves into PCI scope.

In this particular example with `last4` and `brand`, we *could* support something like that because these pieces of information aren't as sensitive as others, but we have not and are not currently planning on building an Element that renders this information.

**Comment by mitchswaldman** [comment]
@jez For sure. Thanks for the response!
