### ISSUE TITLE
"disabled" inputs

### ISSUE THREAD

**Issue by andresmatasuarez** [stripe/react-stripe-elements#132]
And that's it, it would be great if we could add the possibility for inputs to be disabled. I have to write a feature where I need to disable a whole form depending on a certain condition, and that form includes some Stripe Element inputs.

What do you think?

**Comment by jenan-stripe** [comment]
Hi @andresmatasuarez! I'd love to hear your use case. Is this something that could be handled external to the elements? (overlays, hiding the element, etc.).

**Comment by andresmatasuarez** [comment]
Recently, i had to do some sort of credit card form where a user could
choose to use an existing credit card or to create a new one. The ideal
scenario was to disable the form if the user chose to use an existing card
and reenable it if he/she instead opted to fill in a new credit card.

Of course, that specific use case has plenty of workarounds but im sure
that situations like that abound.

Anyway, i believe that the possibility to treat Stripe elements in a
similar manner to regular inputs can do only good,  improving flexibility
and interoperability between components for instance

**Comment by jez** [comment]
Hey @andresmatasuarez, this would be really cool! But like you mention, it should already be possible to achieve this effect without changes to Stripe.js. Because of that, I'm going to close this for now.

That being said, if you can think of a way to implement this in react-stripe-elements (i.e., without changes to Stripe.js) with a clean API, that'd be great! If this is something you're interested in working on, you could open up an API review process to get feedback on your planned approach:

https://github.com/stripe/react-stripe-elements/blob/master/.github/API_REVIEW.md

Thanks again for wanting to help improve react-stripe-elements!
