### ISSUE TITLE
PostalCode validation response contains value directly instead of the nested postalCode field

### ISSUE THREAD

**Issue by sameerbhadouria** [stripe/react-stripe-elements#156]
Feature request or idea? Consider opening an [API review](.github/API_REVIEW.md)!

### Summary

PostalCode validation response contains value directly instead of the nested postalCode field

### Other information
The postal code change event should return the following object:
```
interface ElementChangeResponse {
   brand: string;
   complete: boolean;
   empty: boolean;
   value?: { postalCode: string | number };
  error?: Error;
}
```
In case of Postal Code, the value should be nested in the postalCode field however, the value is being returned directly in the value field itself.

![image](https://user-images.githubusercontent.com/1181565/35131622-0c679b48-fc7c-11e7-9629-0f99d4f936b7.png)

Not specific to the browser

**Comment by atty-stripe** [comment]
Hi @sameerbhadouria! Do you mean that you would like the value to be nested, or that the docs suggest the value will be nested, but isn't?

Per Stripe.js docs, the `value` field will directly contain the Element's value, when it is not sensitive data: https://stripe.com/docs/stripe-js/reference#element-on.

**Comment by cweiss-stripe** [comment]
Hi @sameerbhadouria 

The behavior of the value being nested for the `card`-Element and not being nested for the `postalCode`- Element is intentional and in-line with our docs (I agree that we could improve them to be clearer on that, though).

The `card` is a multi-field Element, hence the values are nested -- the `postalCode` field only contains one input, hence the value is not nested.

To create a `card` Element with a prefilled postal code you would do the following:
```js
elements.create('card', {
  style,
  value: {
     postalCode: '94110'
  }
})
```

To create a `postalCode` Element with a prefilled value you would do:
```js
elements.create('postalCode', {
  style,
  value: '94110',
});
```

Correspondingly, the `value` in the change event is nested (`card`-Element) and not nested (`postalCode`-Element)
