### ISSUE TITLE
Safari Mobile keeps virtual keyboard open on submit

### ISSUE THREAD

**Issue by MovingGifts** [stripe/react-stripe-elements#161]
After the `CardElement` field is filled out, hit Pay, you will see that it triggers the blur (since that is where the alert test is to see if the field actually blurs). In Safari Mobile, the way to make the virtual keyboard disappear is hitting the Done button or causing the focused field to blur. If a user hits the Pay button in the window, (without hitting the done first, which is very normal), the virtual keyboard should disappear, since the field is blurred. Not sure how to fix this issue after some long hours on it.

Tested on Safari mobile on iPhone. [Here's a fiddle showing the issue.](
https://jsfiddle.net/g9rm5qkt/86/)

**Comment by asolove-stripe** [comment]
Hi @MovingGifts, thanks for your report! I just wanted to add a note here saying we are aware of this and considering ways to resolve it.

The problem comes from some odd Safari Mobile behavior. When switching focus between an iframe and a parent document, blur events in the iframe don't reliably get fired. 

We know of one possible fix: in the click handler for the pay button, add code to re-focus and re-blur the element after the form is submitted, which will force the keyboard to hide. [Here's an updated version of your fiddle that works for me on Mobile Safari](https://jsfiddle.net/5u2afmqr/8/).

We are reluctant to put this fix into the library code, because applications may have their own complex focus or animation logic that would get messed up by this re-focus and re-blur. But if it works for your use-case, adding this to your integration should get rid of this problem.

**Comment by MovingGifts** [comment]
Hi @asolove-stripe, the possible fix shown in your fiddle works correctly (it hides the mobile safari virtual keyboard on form submit). Thanks for providing a workaround solution to this issue.
