### ISSUE TITLE
CardNumberElement

### ISSUE THREAD

**Issue by hlrd93** [stripe/react-stripe-elements#165]
CardNumberElement does not display [Visa, Mastercard] icon.

**Comment by jez** [comment]
👋 Hey! This is intentional. The `CardElement` is the input you should use if you want all the bells and whistles (like icons). The `CardNumberElement` is purposefully plain so that you can implement your form however you see fit. We are *not* planning on adding icon support to the CardNumberElement.

If you don't want to use the `CardElement`, you should listen to the change event, which will report the card brand as a part of the change event message.

**Comment by neslinesli93** [comment]
`CardElement` is wonderful, but unfortunately there is no way to remove Zip Code entering/validation...

**Comment by atty-stripe** [comment]
@neslinesli93 you can pass in `hidePostalCode: true` when creating the Element if you want to remove the postal code field. More details here: https://stripe.com/docs/stripe-js/reference#element-options.

**Comment by tonag** [comment]
@atty-stripe  it seems that in v3 hidePostalCode seems not to work as you can see from this fiddle.  https://jsfiddle.net/ywain/5yz4z2yn/
Any idea?

**Comment by atty-stripe** [comment]
@tonag the "ZIP code" field in that example seems to be from the HTML, and not related to Stripe Elements. `hidePostalCode` hides the postal code field within the `card` Element.

**Comment by IanLunn** [comment]
For anyone coming here looking to disable the zip/postal code for react-stripe-elements:

```
<CardElement hidePostalCode={true} />
```

**Comment by Hongdeshuai** [comment]
Thank you.

**Comment by spicymaya** [comment]
The above didn't work for me. But providing options object instead worked.
`<CardElement options={{hidePostalCode: true}} />`
