### ISSUE TITLE
Error: You did not specify the type of Source or Token to create

### ISSUE THREAD

**Issue by saurishkar** [stripe/react-stripe-elements#167]
### Summary

I am still facing an issue with the **Error: You did not specify the type of Source or Token to create.We could not infer which Element you want to use for this operation.**

I have a **CardAdd** component that is a simple form with just one element: 

```
import React, { Component } from 'react';
import { injectStripe } from 'react-stripe-elements';

class CardAdd extends Component {
  constructor(props) {
    super(props);
    this.state = {input: ''};
    this.handleFormSubmit = this.handleFormSubmit.bind(this);
    this.handleInputChange = this.handleInputChange.bind(this);
  }

  handleFormSubmit(event, values) {
  	event.preventDefault();
  	const promise = this.props.stripe.createToken({type: 'card', name: 'sample'});
  	promise.then((response) => {
  		console.log('response', response);
  	}).catch((err) => {
  		console.log('error', err);
  	});
  }

  handleInputChange(event) {
  	this.setState({
  		input: event.target.value
  	});
  }

  render() {
  	// const { handleSubmit } = this.props;
    return (
      <div>
        <form className="add-card-form" onSubmit={this.handleFormSubmit}>
          <a className="closeBtn" onClick={() => this.props.closeModal()}><span className="icon icon-close">&times;</span></a>
          <div className="sbs-row">
            <div className="sbs-col-12">
              <input type="number" name="credit_card[number]" label="Card Number" placeholder="Your Card Number" onChange={this.handleInputChange} />
            </div>
          </div>
          
          <button type="submit">Add</button>
        </form>
      </div>
    );
  }
}

export default injectStripe(CardAdd);

```

I have a **CardList** component that basically mounts the **CardAdd** component as a collapsible component.

```
import React, { Component } from 'react';
import { Elements, StripeProvider } from 'react-stripe-elements';

import AddCard from './add';
import SECRETS from '../../../constants/app-secrets';

class CardList extends Component {
  constructor(props) {
    super(props);
    this.state = {
      showAddModal: false
    };
    this.openAddModal = this.openAddModal.bind(this);
    this.closeAddModal = this.closeAddModal.bind(this);
  }

  openAddModal() {
  	this.setState({
  		showAddModal: true
  	});
  }

  closeAddModal() {
  	this.setState({
  		showAddModal: false
  	});
  }

  render() {
    return (
      <div className="card-list">
        <button className="add-card-btn" onClick={this.openAddModal}>Add Card</button>
        { this.state.showAddModal && <Elements><AddCard closeModal={this.closeAddModal} /></Elements>}
        <div className="sbs-row">
        	<div className="sbs-col-12">
        		Here you can see the list of all cards.
        	</div>
        </div>
      </div>
    );
  }
}

export default CardList;

```

My App Component where i attach the provider:

```
class App extends Component {
  render() {
    return (
      <StripeProvider apiKey={SECRETS.stripeApiKey}>
        <Provider store={createStoreWithMiddleware(reducers)}>
          <BrowserRouter>
            <div>
              {configRoutes()}
            </div>
          </BrowserRouter>
        </Provider>
      </StripeProvider>
    );
  }
}
```

On filling the values and submitting it (using the a sample value gives me the error mentioned above).
Initially, this was implemented with redux-form, i just tried to test it on a simple form ( thought redux form might be doing something to it) but it's still gives the same error.

### Other information

Version : 1.4.1,
Browser: Chrome
OS: Mac OS Sierra

#55 #40

**Comment by asolove-stripe** [comment]
Hi @saurishkar! In your `CardAdd` component, it looks like you are rendering a text input to collect the card number. To use Stripe Elements, you'll want to instead render one of our components, like `CardElement`, to collect the card information. If you've rendered one of our components, then `this.props.stripe.createToken()` will get you a token for the card number collected inside the component. ([Here's an example of a form using our `CardElement` component](https://github.com/stripe/react-stripe-elements/blob/master/demo/demo/index.js#L55).)

Now, you might ask: why do you have to use the UI components from Stripe Elements rather than styling your own UI and then creating a token with the information you gather? The reason is security! When you render a Stripe Element, it is rendered inside an iframe that your site can't directly access. As a result, only Stripe card ever touches the raw card number, meaning that your site can go through a much less rigorous PCI audit than if you collected the card number yourself.

**Comment by asolove-stripe** [comment]
I'm going to close this since I don't think there's anything to be fixed in this library. Feel free to reach out to [Stripe Support](https://support.stripe.com) if you want further help with Elements as a product!
