### ISSUE TITLE
any way to use stripe 3 without all the ui of this library? with just simple fields like in v2

### ISSUE THREAD

**Issue by ttaranov** [stripe/react-stripe-elements#19]
This library adds quite a bit of overhead to a react app - but I do still want to use Stripe directly in React app. Documentation on stripe.com is not clear and refers a lot to various css styling issues to create a 'card' before creating a token.

In other words, I'd like something like the following:
1) npm install stripe --save
2) import stripe; 
3) stripe(mykey).createToken({cc:ccVal,exp:expVal,cvc:cvcVal}).then(...)

how do I do this? (without reverting to stripe v2)

**Comment by jenan-stripe** [comment]
Hi @ttaranov! You can't access the card information directly for security reasons in the latest version of Stripe.js. If there's something specific from Elements or Stripe.js that you need, please write in to support: support@stripe.com -- thanks!

**Comment by ttaranov** [comment]
I guess I'll then stay on v2 - it works fine with react apps I need... thanks!

**Comment by Lehakos** [comment]
Can you add ability to choose custom component for elements? Like how is this done in the redux-form https://redux-form.com/7.3.0/examples/react-widgets/

**Comment by suprMax** [comment]
is there a link to v2 documentation somewhere? i would prefer to use least amount of 3rd party code possible

**Comment by atty-stripe** [comment]
To expand on Jenan's comment above, using Stripe.js v2 will subject you to PCI SAQ A-EP level compliance, which requires you to upload your [A-EP form](https://www.pcisecuritystandards.org/documents/PCI-DSS-v3_2-SAQ-A_EP-rev1_1.pdf) to Stripe to verify compliance (usually a good amount of work.)

To maintain the simplest level of PCI compliance, Elements renders form inputs within iframes, while allowing complete customization using Stripe.js v3 APIs. As such, we highly recommend you use Stripe.js v3 and Elements to build your credit card form.

You can learn more about the different levels of PCI compliance on our [integration security guide](https://stripe.com/docs/security).

**Comment by farahabdi** [comment]
@atty-stripe thanks for the info, but I really don't want to use your elements. They are pretty good for instant integration but awful when you need a very specific look and feel.

**Comment by fred-stripe** [comment]
Hi, @farahabdi! We've designed Elements to be as flexible as possible for custom styles while balancing strict [PCI requirements](https://stripe.com/docs/security#validating-pci-compliance) for handling sensitive card information. I'd recommend taking a look at the official [Elements Examples](https://stripe.github.io/elements-examples/), which has a variety examples of customization using the `style` property of each Element. If you are having difficulty achieving a specific style, support@stripe.com would be happy to help!

@suprMax what you've mentioned here is a part of [Radar](https://stripe.com/docs/radar#requirements), which identifies anomalous device behavior in order to protect your business against fraudulent activity. I'd recommend contacting email support if you have any questions about this!
