### ISSUE TITLE
CardElement submit on enter seems to fail because of html5 required / pattern

### ISSUE THREAD

**Issue by yamsellem** [stripe/react-stripe-elements#193]
### Summary

Entering a card and using the enter key in a stripe CardElement refuses to call the `handleSubmit` function and reveal an HTML5 error "Please match the requested format". Meanwhile using a click handler on a button works fine. Here's the code. Thanks for your help.

```javascript
import React from 'react';
import {CardElement, injectStripe} from 'react-stripe-elements';

class Pay extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            loading: false
        };
    }
    handleSubmit(event) {
        event.preventDefault();

        if (!this.props.stripe)
            return;

        this.setState({loading: true});
        
        this.props.stripe.createToken().then(({token}) => {
            this.setState({loading: false});
            console.log(token);
        })
        .catch(err => {
            console.log(err);
        });
    }
    render() {
        return (
            <form onSubmit={this.handleSubmit.bind(this)}>
                <div class="stripe">
                    <CardElement hidePostalCode={true} style={{base: {
                        fontSize: '15px',
                        fontFamily: '"Lato", sans-serif'
                    }}} />
                </div>
                <div class="buttons">
                    <button class="button is-primary is-fluid" onClick={this.handleSubmit.bind(this)}>
                        Payer
                    </button>
                </div>
            </form>
        );
    }
}
  
export default injectStripe(PayForm);
```

In another component:

```javascript
<StripeProvider apiKey={process.env.stripe.key}>
    <Elements>
        <Pay />
    </Elements>
</StripeProvider>
````

### Other information

![required](https://user-images.githubusercontent.com/606754/38132031-a8e98e94-3409-11e8-9e71-e764237e54b4.png)

React Stripe Elements 1.6.0
Chrome Version 65.0.3325.181

React 16.2.0
ReactDOM 16.2.0

Webpack 4.1.0
Babel-core 6.26.0
Babel-loader 7.1.3

**Comment by yamsellem** [comment]
This error seems to only happens when entering the "toggle device toolbar" on Chrome and entering a phone responsive mode. Then, even after leaving this mobile responsive mode, the error stays. Maybe it's not relevant and only related to the Chrome simulator and not to Stripe Elements.

After a test with the Chrome remote device (_on a dev machine_), on mobile, the form enter key (_the keyboard > on Android, on the bottom right corner_) only hide the keyboard and do not submit the form. May this is related.

**Comment by asolove-stripe** [comment]
Hi @yamsellem, thanks for reporting this. Sorry for the slow reply, I was trying to reproduce and had a hard time doing so. After some trying, I am able to reproduce the enter key difference between desktop/mobile, but I am not able to reproduce the required bug when switching to phone mode.

Can you let me know what specific options you're picking for phone responsive mode? In particular, what size is the screen or are you specifying a custom user agent string? And what version of Chrome are you on?

**Comment by garyforsterio** [comment]
+1. Having the same issue using both chrome dev tools, where the error `Please match the format requested` appears 
![error](https://user-images.githubusercontent.com/14568655/40156170-b70433fa-59d2-11e8-8fb3-1ba090f78abd.png)

and also on my pixel 2 using chrome v66.0.3359.158 where the > key just hides the keyboard rather than submitting the form

**Comment by cweiss-stripe** [comment]
I looked into the Chrome Mobile issue and the reason why the <kbd>→</kbd> key does not submit the form is the following:
On Chrome Mobile, the ">" key either has the functionality of "go to the next field in the form" or "submit the form" if the last input field in the form is focused.
We use some hidden and disabled inputs inside our Elements to manage focus between multiple Elements, so pressing <kbd>Tab</kbd> advances the focus to the next HTML input field or Stripe Element on the page. One of the hidden inputs is positioned after the actual input field in the DOM tree. Hence Chrome Mobile does not switch the functionality of the <kbd>→</kbd> key to "submit the form", because the focused input is not the last one in the form.
This seems like an issue that we can not fix without compromising the keyboard and screenreader accessibility of Elements.

**Comment by asolove-stripe** [comment]
I just tested this and I think it is either resolved or possibly a Chrome Dev Tools bug with slightly more elaborate reproduction steps. The html validation error message does not appear when testing either on desktop Chrome or on real Chrome on iOS or Android. And it also doesn't appear for me in Chrome 69 on Mac when toggling the mobile mode as described above.

If someone can still reproduce this, would love to learn more and resolve, but until then I think I will close.
