### ISSUE TITLE
Add `LegalEntityElement` element

### ISSUE THREAD

**Issue by jferrettiboke** [stripe/react-stripe-elements#194]
Hi all!

This is a feature request. It would be really nice to have an official `LegalEntityElement` element in order to mitigate all extra work when creating or updating connected accounts. This would be similar to `CardElement` but with all data for the legal entity depending of the country.

Here my proposal.

```jsx
// ...

LegalEntityElement.defaultProps = {
  showAdditionalFields: false,
  requireAdditionalFields: false,
  values: {},
  style: {}
};

LegalEntityElement.propTypes = {
  // The country of the account
  country: PropTypes.string.isRequired,

  // The legal entity type
  type: PropTypes.oneOf(["individual", "company"]).isRequired,

  // Shows additional fields on the UI
  showAdditionalFields: PropTypes.bool,

  // Requires additional fields on the UI if `showsAdditionaFields` is `true`
  requireAdditionalFields: PropTypes.bool,

  // Values shown on the UI (only for updating)
  values: PropTypes.object,

  // Returns the token if no error occurs
  onCreatedToken: PropTypes.func,

  // Styles
  style: PropTypes.shape({
    // ...
  })
};
```

This component must (among others):

- Resolve fields according to the country and legal entity type
- Require fields needed on the UI
- Translate and handle all the localization according to the country and legal entity type selected by user
- Must structure fields in a well-defined way depending of the country (date of birth, ordering address fields, etc)
- Update fields only when the new values entered by user are different to the previous ones
- Allow to style it
- Handle document verifications? (I am not sure about this - Maybe another element?)

I think having this is really good. In order to tackle this and make it customizable, I think we should consider other sub-elements such as `AddressElement`, `AdditionalOwnersElement`, etc.

This is only a first quick proposal. We can discuss it deeply in order to refine it.

**Comment by jez** [comment]
Hey @jferrettiboke! Thanks for writing this up.

In order to build this feature into react-stripe-elements, we'd first have to add a new Element type to Stripe.js (react-stripe-elements is just a thin wrapper for React. It aims to not deviate significantly from Stripe.js so that people not using React can benefit equally).

We're tracking feature requests to Stripe.js internally to Stripe. Specific Elements to help with Connect onboarding and data collection is a frequent request, so while we have no immediate plans to build it, it's very likely we'll revisit adding them in the future.

Thanks again for writing in!
