### ISSUE TITLE
Allow usage of the inject HOC outside of an <Elements/> component

### ISSUE THREAD

**Issue by peeinears** [stripe/react-stripe-elements#214]
#### Summary

Allow usage of the `injectStripe` HOC outside of an `<Elements/>` component in order for components to access the Stripe client that `<StripeProvider/>` provides (when not using Stripe Elements).

#### Motivation

I'm using this library for Stripe elements in one part of my app and it's great. In another part of my app I'm using Stripe directly to create a bank account (which is not provided by Elements). I'm already using `<StripeProvider/>`. I know that I could access the Stripe client directly via context but I lose (or have to duplicate) the logic that deals with the context differences between sync vs async ([mainly this](https://github.com/stripe/react-stripe-elements/blob/master/src/components/inject.js#L55-L76)).

#### Alternatives

Provide an additional `inject` HOC that has no Elements specific logic.

#### Scope

The `inject` HOC.

#### Risks

Users who intend to use the `inject` HOC with Elements may not get alerted when setting up the components incorrectly.

**Comment by jez** [comment]
Hey @peeinears! Thanks for opening this API review up.

I believe this should be a use case that is already supported with the existing API surface area. In particular, you should be able to follow this section in the README under "Advanced integrations":

[Using an existing Stripe instance](https://github.com/stripe/react-stripe-elements#using-an-existing-stripe-instance)

> In some projects, part of the project uses React, while another part doesn't. For example, maybe you have business logic and view logic separate. Or maybe you use `react-stripe-elements` for your credit card form, but use Stripe.js APIs directly for tokenizing bank account information.

I believe this is exactly the use case you describe above.

The way this would work is higher up in your component tree, you'd create a `stripe` instance and save it into component state or store it in something like a Redux store. You'd use that `stripe` instance both to create the `<StripeProvider />` and to pass to wherever you create bank tokens.

**Comment by peeinears** [comment]
@jez Woops, missed that! Yeah, I guess I was thinking I wouldn't have to use the `<Elements/>` component at (since I'm not using Elements in this part of the code). Are there any implications with putting `<Elements/>` right below `<StripeProvider/>` as opposed to using it just immediately above the components that use Stripe Elements?

**Comment by jez** [comment]
If you're asking about performance, it shouldn't matter where in the hierarchy the `<Elements />` component is.

There's a bit of subtly around where `<Elements />` and `injectStripe` are with respect to each other. In particular, the component you call `injectStripe` on must not reference `<Elements />`. But generally you'll know if you did this right because it will fail loudly otherwise.

The only other thing is that if for whatever reason you have, for example, two card elements on the same page, when you call `createToken` we won't know which one to use if they're both under the same `<Elements />` component. In that case, you'd need to push the `<Elements />` container down far enough so that you can wrap each `<CardElement />` in its own `<Elements />` container.

If this is hard to visualize, see the demo:

https://github.com/stripe/react-stripe-elements/blob/master/demo/demo/index.js#L338-L343

we have to do this because on the demo page, there's both a `<CardElement />` and `<CardNumberElement />`, both of which can create tokens or card sources, so when you call `createToken` we don't know which one to use.

(But it's fine to mix and match, having both a `<CardElement />` and an `<IbanElement />` under the same `<Elements />` group, because only the `<CardElement />` can create card tokens, and only the `<IbanElement />` can create `sepa_debit` sources.)

**Comment by peeinears** [comment]
Got it, thanks. That makes sense.

It still feels unintuitive to me that I would need the `<Elements/>` component for `inject` even when I'm not using Elements, especially knowing that `<Elements>` doesn't add any value in that case (correct me if I'm wrong). So I still think the requested update could be useful.

That said, I realize this is the *Elements* library, and understand if this non-Elements use case is not high priority or within scope. I defer to y'all!

Thanks for your help and consideration.

**Comment by jez** [comment]
Without `<Elements />`, you'd have to manually keep track of all the element `ref`s that get created when mounting, say, a `<CardElement />`. In the non-React version of Elements, you have to keep track of these element references, and pass them as arguments to `createToken`. In the react version, we can automatically keep track of them for you, so you don't have to pass them to `createToken`.

If you never mount a `<CardElement />` or other individual element, I don't *think* you need `react-stripe-elements` at all. You can just use Stripe.js directly in your page.

**Comment by peeinears** [comment]
Toootallly. I am using `react-stripe-elements` elsewhere, so it's already in my bundle, and since it comes with `<StripeProvider/>` and `inject` (which I like!) I figured I'd use them. Just saw an opportunity to make the provider/inject pattern more generalized. Thanks :)

**Comment by jez** [comment]
👍 closing because I think this is mostly resolved / won't do.

Thanks!
