### ISSUE TITLE
CardElement: when card number is invalid user focus cannot go to other form inputs

### ISSUE THREAD

**Issue by andreafdaf** [stripe/react-stripe-elements#23]
Hello!

When using CardElement in a form that contains also other input fields unrelated to Stripe, if I insert an invalid card number and then try to click another input field the cursor is always brought back to the CardElement input field.
If the card number is empty or valid this doesn't happen. How is that? Thanks :)

PS: I'm using redux-form

**Comment by michelle** [comment]
Hi! Could you put together a minimal reproduction of your issue, perhaps in jsfiddle? https://jsfiddle.net/

You can use the React base fiddle: https://jsfiddle.net/reactjs/69z2wepo/

**Comment by kewitz** [comment]
I just experienced the same issue.
Apparently Stripe's component uses the label selector to deal with focus logic.
If your sibling inputs are not wrapped with a `label` tag, Stripe Element will hold the focus to itself.
This also means that dropdowns won't work in that condition because they will lose focus and close as soon as the element loses focus.

```jsx
<div>
  <label>
    <input />
  </label>
  <label>
    <IbanElement />
  </label>
</div>
```
