### ISSUE TITLE
Incorrect postal/zip text shown when error is made. 

### ISSUE THREAD

**Issue by davidpatters0n** [stripe/react-stripe-elements#233]
### Summary

When you enter a US card number and do not enter a zip code the error message returned is: 

> Your postal code is incomplete.

Surely the correct text based on the card, in this case would be "Your zip code is incomplete"

### Other information

Screenshot for reference
![image](https://user-images.githubusercontent.com/870447/44273012-4bcf8a80-a20c-11e8-8171-899f05d18606.png)

**Comment by HamadaBrest** [comment]
Hi, I noticied this too, is it fixed yet ?

**Comment by fred-stripe** [comment]
Hey folks, this is a great suggestion—the error message actually comes from Stripe.js / Elements itself so any fix will have to be upstream. We're considering making that happen in a future update to Stripe.js but don't have any definite timeline to share on this. Because the required fix lies outside of this library I'm going to go ahead and close this issue for now so that we can focus on the other issues in the library.
