### ISSUE TITLE
API Review: Rename Elements locale prop to initialLocale

### ISSUE THREAD

**Issue by asolove-stripe** [stripe/react-stripe-elements#246]
r? @atty-stripe 

# Background
Stripe.js is unable to update the locale of an already-created element. But RSE allows users to pass in a `locale` prop which they might reasonably expect to update the element's locale if they change the value passed in on a subsequent re-render. We should rename this prop to be clearer that you can only pick the value once, when the `Elements` component is first mounted.

# The proposed change
```diff
type ElementsProps = {
-  locale?: string,
+  initialLocale?: string,
  fonts?: Array<Object>,
  // The full specification for `elements()` options is here: https://stripe.com/docs/elements/reference#elements-options
};
```

# Upgrade path
In the new version that first supports `initialLocale`, we should emit a `console.warn` if users still pass in `locale`.

# Documentation
The largest problem I foresee is that users of an older version of RSE might come to this page and see the new docs. I suggest we should leave both options in the Readme and annotate the versions each one is applicable to.

**Comment by atty-stripe** [comment]
Thanks for the API review!

Implementing the chnage will require a few more things:
- Cutting a minor version to introduce `initialLocale` along with a warning around using `locale`
- Eventually cutting a major version to remove usage of `locale`, which will require explicit code to not allow this prop that is otherwise allowed by Stripe.js
- Documentation to say that all props match with Stripe.js, except this one

I'm a bit hesitant to create a mismatch between RSE and Stripe.js. Have we explored what it'll take to make `locale` actually reactive? (Since this isn't an urgent change, we could expend the effort to implement reactivity instead.)

What do you think?
