### ISSUE TITLE
Save card option

### ISSUE THREAD

**Issue by leotm** [stripe/react-stripe-elements#260]
Is there an option to allow the user to save/retrieve/update/delete their card?

I've noted [cards](https://stripe.com/docs/api#cards) and [create card token](https://stripe.com/docs/api#create_card_token)

Cheers

**Comment by fred-stripe** [comment]
Hi @leotm, this library is designed to be a thin wrapper around Stripe Elements. Updating and managing a customer's list of cards requires both frontend and backend changes, and so is out of scope for this library.

The approach I'd recommend here is using our components to create a card token or source, and then sending that to your server-side application which would then save the card on a customer. For updating a card, I'd recommend sending a list of the customer's current cards (with last4, brand, and expiration) to your frontend, and then building a UI that allows your customer to edit current cards, delete cards, or [add a new card](https://stripe.com/docs/saving-cards). Finally, it is possible to update a card's expiration date and billing address through the Stripe API, but you'd need to send the new information to your server-side code in order to [update the stored card through the Stripe API](https://stripe.com/docs/api#update_card-exp_month).

Hope that clears things up!

**Comment by leotm** [comment]
Thanks @fred-stripe for the quick reply!

I note your suggestions regarding [this.props.stripe.createToken](https://stripe.com/docs/stripe-js/reference#stripe-create-token) or [this.props.stripe.createSource](https://stripe.com/docs/stripe-js/reference#stripe-create-source).
Is one favoured over the other depending on certain circumstances?
One implementation we are considering is using neither on the two above functions, but instead to add a 'Save this card?' checkbox, which could instruct the back-end to create a saved card ID, which could be added/persisted to a user's authentication session, then in future checked for when they make further Stripe payments.
What do you think of this approach?

Many thanks
