### ISSUE TITLE
It is possible to enter card number in a wrong format via CardNumberElement

### ISSUE THREAD

**Issue by eugenkr** [stripe/react-stripe-elements#264]
If you type pretty much quickly it is possible to enter card number in a wrong format. Entered card number can be less than 16 numbers:
![wrong card number](https://user-images.githubusercontent.com/294662/47154485-2124af80-d2eb-11e8-94d5-ab55901dd0e7.gif)
Reproducible at least in Chrome 69 on Mac OS and Windows 10. 
Also I was able to reproduce it on your demo page here https://jsfiddle.net/attystripe/xux7qzch/

**Comment by atty-stripe** [comment]
Hi @eugenkr, you are able to type a 15 digit card number in the GIF because the number fits the Amex card pattern, and Amex cards can be 15 digits long. I tried to repro your issue separately, but always found the Element validated the input. Further, calling createToken or createSource runs a second round of validation, so invalid input will never be accepted.
