### ISSUE TITLE
zip code field behave differently between test and live

### ISSUE THREAD

**Issue by billdevcode** [stripe/react-stripe-elements#287]
### Summary

- On version 2.0.1

Not sure if this was brought up or if this was intentional but on `test` mode, zip code is `complete` once there are 5 digits but on `live` mode, it becomes `complete` with just 1 digit.

### Other information

We can see the value is only `9` but it has the class `is-complete`. The cc number, expiration and cvc input fields all have values and are `complete`.

![screen shot 2018-12-10 at 1 37 24 pm](https://user-images.githubusercontent.com/16677967/49763264-00406100-fc81-11e8-905f-83e651e30d28.png)

**Comment by cweiss-stripe** [comment]
Hi @billdevcode 

This is likely because the card you are testing with (is it 4242 4242 4242 4242?)  is a testmode only card. It is well defined in testmode and its BIN indicates that it is a US card. Therefore we can require the user to enter a 5-digit US ZIP code. In livemode, the card is not recognized as a US card and therefore the postal code requirements are less strict.
