### ISSUE TITLE
Focus -> Blur -> Focus IOS Safari 

### ISSUE THREAD

**Issue by pizza-r0b** [stripe/react-stripe-elements#326]
In IOS safari when moving from one focused field to another via tab, click, or arrow on IOS, the focus event for the new field will fire and then the blur event and then focus again

**Comment by pizza-r0b** [comment]
I am able to reproduce this in the fiddle in the README https://jsfiddle.net/attystripe/xux7qzch/ on the IOS simulator

**Comment by asolove-stripe** [comment]
Hi @pizza-r0b, thanks for this report and sorry for the unfortunate problem here.

It is an unfortunate problem, but it is also currently the side-effect of our attempt to fix an even more unfortunate problem. Under some circumstances, iOS Safari fails to send blur events when focus is moving between iframes. This broke a number of Elements users who never received blur events for inputs that had in fact lost focus. Our imperfect solution for this problem is that when focus is moved out of an Element and the blur event fails to fire, we move focus back, then forcibly blur so the event fires, and then move focus to the newly-focused item. We understand that this causes the newly-focused item to receive double events, but it seems to be the only way to prevent blur events from totally failing to fire. That seemed like the right tradeoff under the circumstances.

If there is something in particular that this is breaking, I'd love to know more and see how we can fix it.

**Comment by pizza-r0b** [comment]
Makes sense. In my case it breaks the way we handle error validation. Once a field is “touched” - which is set to true once a field is blurred - a validation will trigger for the input field. However, with the solution you guys have implemented touched will be set to true when moving from one field to another and the validation will fire before the user has started typing. So if there is a validation to check an empty string then the error will show up as soon as the user focuses the field.

**Comment by asolove-stripe** [comment]
Ah, that's certainly unfortunate. And I'm guessing the field that gets this inappropriate blur is one you control, rather than a Stripe Element, yes? 

Maybe you can clear the validation state when the field is re-focused and empty? And if there's a problem with it quickly switching to invalid and then back, maybe do it asynchronously so it only triggers if there's a blur and no re-focus within 50ms or so?

I definitely understand that this situation is unfortunate, but there's also not a lot we can do to fix it on the Elements side without breaking folks who rely on the blur event getting fired.
