### ISSUE TITLE
How to override default styles

### ISSUE THREAD

**Issue by Stophface** [stripe/react-stripe-elements#356]
I am a little confused how to style the stripe input elements

This is the parent class Billing.

**Billing.jsx**
```
....
render() {
        return (
            <div>
                <Elements >
                    <CcCVC />
                </Elements>
                <Elements>
                    <CcExpiryDate />
                </Elements>
                <Elements>
                    <CcNumber />
                </Elements>
            </div>
        )

```
This is the CcCVC input field

**CcCVC.jsx**
```
...
render() {
        return (
               ...
                <CardCVCElement
                    classes={
                        {
                            base: 'cc-base',
                            invalid: 'cc-invalid',
                            focus: 'cc-focus',
                        }
                    } />
            ...
        )
```
My styles are applied to the wrapping `div`. When the filled input field is invalid, it uses my style AND this style `.InputElement.is-invalid` (which is applied directly to the `input`, not the wrapping div!), making the numbers red. It does not use the default `StripeElement--invalid` style though. However, I only want my style to be applied...

I am also confused how to apply my font styles to the input field. Lets say, I want the typed input to be 'green'. At the moment, it uses the default color style from striped although I am defining a color in `cc-base`.

**Comment by bradlocking** [comment]
Would be great if there were any additional pointers for this ^

**Comment by atty-stripe** [comment]
@bradlocking here's a link to our reference that covers this: https://stripe.com/docs/stripe-js/reference#element-options.

Each Element has an outer container div that your classes are applied to, and an inner input that is rendered within an iframe (for PCI compliance reasons). As such, your classnames do not apply to the inner input. To style the inner input, you must specify styles through JavaScript, as listed in the reference section above.

Here's an example: https://jsfiddle.net/jenanwise/mnpkvtt1/.

Also, looking at your code, you should only have one `<Elements>` container that wraps all the individual components, rather than creating a new `<Elements>` container for each field component.

**Comment by AndrewWreford** [comment]
The styled place for the input field on ma stripe is not showing.plz help
