### ISSUE TITLE
Apple Pay on Safari PWA not working

### ISSUE THREAD

**Issue by leelongmore** [stripe/react-stripe-elements#363]
### Summary

The Apple Pay button (PaymentRequestButtonElement) is working as expected on mobile and desktop Safari.

On a Safari PWA, the button is displayed and when touched will reveal the Apple Pay interface. But after fingerprint recognition completes, the Apple interface reports that it is processing for about 20 seconds and then reports ’Apple Pay Not Completed - The website was not able to complete the payment. Please try again.’

I do however see the following Stripe API requests for the attempted payment: POST /v1/payment_intents, POST /v1/tokens/, POST /v1/payment_methods. But I don't see the final POST to confirm the payment intent.

So I suspect that the "paymentRequest.on('paymentmethod', async event => { ..." code isn't being triggered.

I have tried to make a payment from within the PWA on iPhone 6, 6s and 7 without success. The button works fine on these platforms when using mobile Safari.

### Other information

The button works on other browsers e.g. "Pay now" on Chrome.

**Comment by asolove-stripe** [comment]
Hey @leelongmore: yikes, that's no good! This appears to be an issue with Stripe.js or our API rather than with this react-stripe-elements repo, and it also looks like I'm going to need to dig into the details of your setup, so could you please email me at asolove@stripe.com? If you have request ids or payment intent ids, that would be extra helpful.

**Comment by asolove-stripe** [comment]
We did some testing on this and, unfortunately, it appears that Apple Pay does not work in Safari PWAs at the moment. Our suggested fall-back is to have load your payment page in a regular Safari window (make the link to it use `target=_top` or some equivalent way to force out of the PWA) so that you can use Apple Pay.

**Comment by jdpowell1** [comment]
Hi @asolove-stripe, I was wondering whether you could shed some more light on why this doesn't work? A link to a Webkit bug would be greatly appreciated so the bug can be tracked directly.

**Comment by jdpowell1** [comment]
Can confirm this issue is fixed on iOS 13.

**Comment by leelongmore** [comment]
Hi everyone,

Thanks for resolving this.

Is it possible to test whether the PWA is running on an iOS 13 device and suppress if not?

I am currently only showing an Apple Pay option when not in PWA mode through this check in my code:

return !window.matchMedia('(display-mode: standalone)').matches

Regards
Lee.
