### ISSUE TITLE
Using Bulma with Strip Elements?

### ISSUE THREAD

**Issue by chobo2** [stripe/react-stripe-elements#370]
Hi

I am using [bulma](https://bulma.io/) and I want to style my controls but I noticed with Expiry Date I am losing the `MM / YY` and it seems to lose state as well(I can't type in any of the boxes).

```
        <div className="field expiry-date-container">
          <label className="label">Expiry Date</label>
          <div className="control">
            <CardExpiryElement className="input is-large" />
          </div>
        </div>
```

classNames is where I am using the bulma classes, is this overriding internal classes?

**Comment by dweedon-stripe** [comment]
The classes are only applied to the wrapping `div` in which we mount the Element, so that shouldn't be an issue, but react-stripe-elements does not generally work well with UI frameworks. You will probably need to recreate the look using the [styling API](https://stripe.com/docs/stripe-js/reference#element-options) we provide.

**Comment by asolove-stripe** [comment]
Hi there! Please let us know if you found a solution or are still having this problem. In the meantime, I am going to close this due to inactivity.

Note that Elements ultimately render content inside iframes, so applying styling to the wrapper element on your page will not directly style the Element itself, just the wrapper. In some circumstances, applying the same styling you would to an input will work. I have a suspicion that in this case, those classNames work well on an input but don't do what you want on a wrapper element where the real input is inside our iframe.

**Comment by CalvinGrain** [comment]
This worked for me
`<style>
.is-input{
    -moz-appearance: none;
    -webkit-appearance: none;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    border: 1px solid transparent;
    border-radius: 4px;
    -webkit-box-shadow: none;
    box-shadow: none;
    display: -webkit-inline-box;
    display: -ms-inline-flexbox;

    font-size: 1rem;
    height: 2.25em;
    -webkit-box-pack: start;
    -ms-flex-pack: start;
    justify-content: flex-start;
    line-height: 1.5;
    padding-bottom: calc(0.375em - 1px);
    padding-left: calc(0.625em - 1px);
    padding-right: calc(0.625em - 1px);
    padding-top: calc(0.675em - 1px);
    position: relative;
    vertical-align: top;
}

.is-input{
    background-color: white;
    border-color: #dbdbdb;
    border-radius: 4px;
    color: #363636;
}

.is-input{
    -webkit-box-shadow: inset 0 1px 2px rgba(10, 10, 10, 0.1);
    box-shadow: inset 0 1px 2px rgba(10, 10, 10, 0.1);
    max-width: 100%;
    width: 100%;
}
</style>`

**Comment by roxigonzalez** [comment]
Same problem here :(
