### ISSUE TITLE
Getting error with createPaymentMethod

### ISSUE THREAD

**Issue by ae3e** [stripe/react-stripe-elements#378]
Hi,

I'm working on the new payment flow to meet SCA regulation.
I followed the [migration guide](https://stripe.com/docs/payments/payment-intents/migration#elements) and so I replaced the method (which works) :

```javascript
let {token} = await this.props.stripe.createToken()
```

by :

```javascript
let {paymentMethod} = await this.props.stripe.createPaymentMethod('card')
```

But I have the following error :

**_IntegrationError: Please provide either an Element or PaymentMethod creation parameters to createPaymentMethod._**

I also tried to pass an empty object as second parameter.
```javascript
let {paymentMethod} = await this.props.stripe.createPaymentMethod('card',{})
```
Then the request is sent but it returns an error with the message `Missing required param: card.` (Elements are not found to fill card's data?? Obviously, they're found with `createToken` method!)

I finally tried to upgrade api version on Stripe dashboard (#354) but without any luck.
Am I missing something or is this a bug (npm package used is `react-stripe-element@4.0.0`) ?

**Comment by shujaattariq** [comment]
I am facing the same issue, works for createSource but not for createPaymentMethod

**Comment by oliver-stripe** [comment]
Hey there! Thanks for the report. Taking a look at this.

**Comment by oliver-stripe** [comment]
Since 3.0.0, this method should automatically find the elements and I was unable to reproduce this on 4.0.0 as well. Can you confirm that an older version of react-stripe-elements is not being used somehow?

I don't believe this is a bug as I haven't been able to reproduce on recent versions. Here's a rough fiddle I used to verify: https://jsfiddle.net/mjrLt082/2/

If you're still running into issues, please reach out to our support team at https://support.stripe.com/contact or come chat with us at #stripe on freenode.

**Comment by ae3e** [comment]
Shame on me !
I was running npm commands in the wrong folder... and so I was not using 4.0.0 release...

Now, it works... I really apologize...

**Comment by tuomashatakka** [comment]
I had similar issues with the createPaymentMethod function not sending card details to the server. Updating from 3.0.0 to 4.0.0 fixed the issue.
