### ISSUE TITLE
update existing card details

### ISSUE THREAD

**Issue by heron2014** [stripe/react-stripe-elements#39]
Is there a way to update existing card details using this library?

**Comment by jenan-stripe** [comment]
Sorry, we don't have anything like that yet!

**Comment by MovingGifts** [comment]
Is this still the case? No way to update existing card details using stripe elements?

**Comment by atty-stripe** [comment]
@MovingGifts if what you want is to show the existing card number in a form, and let the user update it, then no, sorry. Stripe abstracts away raw credit card details via Tokens, and this would require having access to the raw number.

However, if what you want is to show a new credit card entry form, allow the user to type in a new number, and save that, you can definitely do that right now. Just create a new Token for the new details, and save that to your Customer.

**Comment by MovingGifts** [comment]
@atty-stripe Got it, thank you for clarifying :)

**Comment by vbk6** [comment]
Any new changes on this issue?

**Comment by abhijithss2010** [comment]
@atty-stripe Any new information on this issue?

**Comment by atty-stripe** [comment]
Sorry folks, I no longer work on this product. It would be useful if you could share the desired end user experience (either in words, or sample design mockups) so we can understand your needs better.

**Comment by hofman-stripe** [comment]
@abhijithss2010 @vbk6, could you clarify your use cases? What part of the card details do you need to update, and in what context?

You can collect and update most [Payment Method](https://stripe.com/docs/api/payment_methods/update) or [Card Sources](https://stripe.com/docs/api/cards/update) fields yourself.

If you want to use a saved card for a payment, but ask the user again for their CVC, you can now do so: https://stripe.com/docs/payments/save-during-payment#web-recollect-cvc

Updating the card number of an existing payment method or source is not possible. What you should do is create a new method / source, attach it to your customer, and optionally [update your customer](https://stripe.com/docs/api/customers/update) to use the new method / source as default.

Please reach out to [Stripe Support](https://support.stripe.com) if you have further questions regarding your integration.

**Comment by AckerApple** [comment]
I am chasing CVC updating. I have come across some notes worth sharing.

- During testing, use card number 4000000000000127 to a have transactions fail for “Charge is declined with an incorrect_cvc code”
  - This sets up the scenario that someone entered a CVC that didn’t fail until transaction attempted
- @hofman-stripe your comment seems to suggest I can only recollect CVC every time as an option
  - The docs you linked do not have an CVC update abilities
- In the case of card expiring and a new CVC being issued, no actions MAYBE required because Stripe auto attempts those types of via communications with card intuition. [Read more here](https://stripe.com/docs/saving-cards#automatic-card-updates)

### Resources

- [demo failure card numbers](https://stripe.com/docs/testing#cards-responses)
