### ISSUE TITLE
Handle payment intent 

### ISSUE THREAD

**Issue by jacklaaa89** [stripe/react-stripe-elements#394]
I am just wondering how to handle payment intents which already have a source attached from the server. When I attempt to handle the payment, passing the intent client secret i get that the card number is not complete. Its not supposed to be as a source is already attached to the intent.

eg, this example:
```js
// intent is generated on the server and already has a payment source attached.
const { stripe } = this.props;
return stripe.handleCardPayment(intent);
```

Can I get some insight on how to handle a payment intent with a source already attached?

Cheers.

**Comment by mbarrett-stripe** [comment]
Hi @jacklaaa89 - sounds like the error is a bit unclear. If I understand your use case correctly, I think the flow your looking for can be found here in our docs on the [manual confirmation flow](https://stripe.com/docs/payments/payment-intents/quickstart#manual-confirmation-flow). `stripe.handleCardPayment` is used for the automatic flow, which includes collecting details from the client for the Payment Method to be attached to the Payment Intent.

Since you already have the method attached, you can confirm on the backend, and then use `stripe.handleCardAction` on the frontend to handle any potential next steps, such as SCA, then talk back to your server to complete the transaction.

I hope that helps!

**Comment by couds** [comment]
Hi, I have a similar issue.

if I try to use the `handleCardPayment` I got the same issue of of `incomplete card number`

if I use the `handleCardAction` I got `handleCardAction: The PaymentIntent supplied does not require manual server-side confirmation. Please use handleCardPayment instead to complete the payment.`

My workflow its the follow:

1. Create a Source on the client side for the Card and send the sourceId to the server
1. Create a customer and attach the source
1. Create a SetupIntent (to handle SCA if necessary on the client side)
1. Later (The user it's offline) I create a new Charge (creating a subscription)
1. Got a Webhook `invoice.payment_failed` with the PaymentIntent
1. Use the `paymentIntents.retrieve` on the server to get the details of the Intent and got status `requires_action` with next_action.type = use_stripe_sdk
1. On the client side I tried to use `handleCardAction`  or `handleCardPayment` but both fails. IDK what else to do.

Thanks!

**Comment by mbarrett-stripe** [comment]
Hey @couds -

Sorry that you're running into this issue. While I did respond to the original question, this repo is really only for issues with `react-stripe-elements`. We have a stellar support team who can help you with your current issue, take a look at [support.stripe.com](https://support.stripe.com/) and shoot them an email or chat message. They'll be able to help you from there.
