### ISSUE TITLE
Content Security Policy | resource at inline (“script-src”)

### ISSUE THREAD

**Issue by rfdc** [stripe/react-stripe-elements#410]
Hi there,

I'm getting the following errors:
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 controller-815299a026a6d6a05ad55cbe5b5816d4.html:1:1
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 elements-inner-card-c196d3b8afe06d267d91d2a6623def46.html:1:1
```
Here is a screenshot for the error:
![image](https://user-images.githubusercontent.com/32999759/63252537-9746c980-c2a2-11e9-8721-c293940ff0a1.png)

These errors are happening only at firefox.

How do I resolve this?

Thanks

​

**Comment by asolove-stripe** [comment]
Hi @rfdc: are you also seeing that the Element is not loading or not behaving correctly, or is it working fine but just showing this error?

This error is saying that something is trying to inject an inline `<script>` tag into the Stripe iframes, which for security reasons do not allow inline scripts. This is usually caused by a browser plugin that is aggressively trying to inject itself into every document and frame. 

If the Element is looking/acting as expected, this error is just letting you know that our security precautions are working.

**Comment by rfdc** [comment]
Hi @asolove-stripe,
It seems to be working fine on dev mode. I'll let you if any issues arises once I launch it then.
Thanks
