### ISSUE TITLE
Why is the use of lineHeight discouraged?

### ISSUE THREAD

**Issue by matchatype** [stripe/react-stripe-elements#438]
Setting `lineHeight` property on base style object will raise the following console warning: 

```
The use of the style property lineHeight is discouraged, because it can lead to visual inconsistencies among various browsers. Consider using a padding on the Element’s container instead.
```

Besides looking just fine in my tests, it's apparently the only way I can set the container height the way I need, and symmetrically so, vertically. Relying only on padding forces me to apply weird rules or height will be an odd measure (i need it even).

### Style prop CardElement is complaining about

```
<CardElement
  style={{
    base: {
      fontSize: '16px,
      fontFamily:
        'Prompt, system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      lineHeight: '24px',
    }
  }}
/>
```

**Comment by mbarrett-stripe** [comment]
Hey @matchatype - while we discourage use of `lineHeight` due to known alignment and rendering issues in some browsers, you can still use it if you've tested it and approve of how everything is rendering in your supported browsers. That message will only display when using a test mode key, so when you use a live key, it will remain silent.

As an example, we've seen cursor rendering issues with larger `lineHeight` values in Safari - so if you support that browser, it might be worth checking that your specific use case looks good for you there.

Hope that helps!

**Comment by matchatype** [comment]
Ok thanks @mbarrett-stripe You nailed it, I was trying to deploy a built project still not in production and the warning bothered me. Thanks for clarifying that!
