### ISSUE TITLE
Calling element.focus() not working on iOS 13+

### ISSUE THREAD

**Issue by yoniweisbrodlemonade** [stripe/react-stripe-elements#441]
Calling `element.focus()` does not seem to focus the element on iOS 13, tested on Safari and Chrome. It does work on older versions of iOS and on Android and desktop. I verified that the element is available, but calling focus doesn't seem to work. Not sure whether this is a bug with React-Stripe-Elements, or with Stripe Elements in general.

**Comment by mbarrett-stripe** [comment]
Hi @yoniweisbrodlemonade - this is, unfortunately, a new bug with iOS 13. Updates to Safari introduced limitations to passing around focus between elements in certain cases. Due to the way that Stripe Elements works, the change catches this use case and prevents the focus from propagating. It is, to be clear, a huge bummer.

This is something we're tracking internally, and I'll make a point to update our docs to reflect this limitation.

And for further clarity, this is a Stripe Elements bug specifically, and not a React-Stripe-Elements bug.

**Comment by pandaiolo** [comment]
I think I am experiencing this bug, and would like to confirm @mbarrett-stripe . It's still open if I believe the `element.focus()` docs.

Basically, we have a form with a bunch of inputs (incl. stripe card) and when a user presses the arrows of iOS virtual keyboard to navigate through the form, the viewports scrolls automatically to follow the focus. 

Unfortunately, because the stripe card is not able to focus the internal iframe input, only the "fake" input is focused, but not scrolled into the view, and it stays hidden behind the virtual keyboard.

This is a consequence of this bug right? Do you have any news about it, if it might be fixed in the future, or not? Possible workarounds?

Thanks for any suggestion to improve UX.
