### ISSUE TITLE
Call handleCardPayment with an existing source on the same form as an Element

### ISSUE THREAD

**Issue by CiaranMn** [stripe/react-stripe-elements#442]
### Summary
The automatic passing of the CardElement is preventing calling handleCardPayment with an existing source (by passing `{ source: <some_source_id> }` as an option) inside the same `<Elements>`.

### Details
I have a form where users can select from existing sources, or enter new card details. Previously (v2.0.3) I called handleCardPayment either (a) NOT passing the CardElement and sending `{ source: <source_id> }` as an option, where source_id was the existing source they had selected from the list, or (b) sending the CardElement from state as per the previous integration.

This is no longer possible because the CardElement is automatically passed into handleCardPayment, and attempting to send a different source results in this error:

```When calling handleCardPayment on an Element, you can't pass in a pre-existing source ID, as a source will be created using the Element.```

I appreciate I could move my 'use an existing source' logic outside of `<Elements>` but it would be a pain. Is it possible to instead NOT to attempt to use the CardElement if `source` has been provided in the options object, or have I missed a way of doing this anyway?

**Comment by fred-stripe** [comment]
Hi @CiaranMn unfortunately this is a current drawback of this library's design. We're working on a way to expose the `Stripe` instance directly so that you can call `handleCardPayment` without passing in an Element.

The current workaround, as mentioned in issue #365, is to use a second `<Elements>` group for the code that needs to call `handleCardPayment`. As an example, `ChooseExistingCard` would be your component that allows your customer to choose from their list of card, and `NewCardForm` is the component that uses a `CardElement` or similar to allow them to enter the new card:

```
<App>
<StripeProvider apiKey="…">
   <Elements>
     <NewCardForm>
           …
           <CardElement />
           …
     </NewCardForm>
   </Elements>
   <Elements>
      <ChooseExistingCard />
   </Elements>
</StripeProvider>
</App>
```

Because there aren't any elements in the second `Elements` component, `this.stripe.handleCardPayment()` will pass the data through to Stripe. If you were to move ChooseExistingCard to the first `Elements` group, then `handleCardPayment` would "find" the CardElement which is the issue you're hitting right now.

There's a comment here that explains the issue:
https://github.com/stripe/react-stripe-elements/blob/6de09a541f30f0ce696ffcef3c66df5210bcf583/src/components/inject.js#L310-L312

I'm going to close this issue for now but tag it so that we can follow up once we've made things a bit simpler to work with!
