### ISSUE TITLE
macOS Safari: focus() does not focus the actual input

### ISSUE THREAD

**Issue by momentpaul** [stripe/react-stripe-elements#454]
When using macOS Safari, if I have a `<CardElement/>` with `onReady={elem => elem.focus()}`, it does not actually focus the input element.  It does trigger the `onFocus` event, but it's not actually focused, and you can't type.  If you hit tab and then shift-tab, it still is not focused.  If you click directly on the input, it will focus the element.  It is also worth noting that the `onBlur` event does not fire on that first tab press.

This works fine in Chrome though.

In Safari, I've also tried using the `ref` prop to invoke `focus()`, but that doesn't work either.  I tried this with version `5.1.0`, but I'm not sure when this started being an issue.

**Comment by mbarrett-stripe** [comment]
Hi @momentpaul. Unfortunately this is a side effect of a change made to the latest [release of Safari](https://developer.apple.com/documentation/safari_release_notes/safari_13_release_notes) which prevents 3rd party iframes from programmatically focusing before the user makes a direct interaction with the frame.

You can replicate this minimally by making a small page with an input and a script that places focus on the input on an interval, then iframing that page cross-domain into another (servers on different ports will have the same effect). The script will not focus the input until the user clicks into the iframe in Safari.

This is a browser level limitation that has changed recently. We're aware of the bug and tracking it internally. I just checked the Stripe.js docs, which only say this affects iOS 13. Since it also affects Safari 13, I'll make a point to update that documentation to reflect this limitation.

**Comment by joshbernfeld** [comment]
I am also experiencing this issue but without any programmatic focusing. The user is unable to use the tab key to move to the next credit card field until the field has been clicked once.

**Comment by mbarrett-stripe** [comment]
@joshbernfeld - please see my comment about this issue [here](https://github.com/stripe/react-stripe-elements/issues/357#issuecomment-595821818)

(for future reference for folks, this is a dupe of #357)
