### ISSUE TITLE
Usage with stripe connect

### ISSUE THREAD

**Issue by tume** [stripe/react-stripe-elements#50]
I was reading documentation about connect (store-builder recipe) and saw mention that I could use Elements or Checkout for collecting the payment details. 

So ended up trying to set this up but run into a small hiccup... if I understood correctly I should be creating the token with connected user’s API key which means I should be changing the apiKey to StripeProvider based on the seller/user. While checking on how to do this I found this: 
https://github.com/stripe/react-stripe-elements/blob/master/src/components/Provider.js#L45

Does this mean that this is not supported? or is the some better way of doing this?

**Comment by michelle** [comment]
Hi! Wouldn't you know the API key you want to use at the Provider's render time? Do you need to switch out the API key dynamically?

**Comment by michelle** [comment]
The issue is that for each API key, we need to create a new instance of `stripe`.

**Comment by tume** [comment]
That's true...I was wrapping my root component with stripeProvider without thinking too much but I guess makes more sense to just wrap the view where the payment happens. 

Thanks 👍

**Comment by michelle** [comment]
@tume also, if you're using tokens instead of sources, you should just be using your platform's publishable key :).

**Comment by realfresh** [comment]
I ended up bumping into this problem as well as I was dynamically changing out the publishable key based on which store location was accepting the order.

In order to completely re-create the stripeProvider component and avoid the error, simply pass a unique key prop to the provider component

`   
<StripeProvider key={stripeSettings.publishable_key} apiKey={stripeSettings.publishable_key></StripeProvider>
`
