### ISSUE TITLE
Error, you may need an appropriate loader to handle this file type while importing from @stripe/react-stripe-js

### ISSUE THREAD

**Issue by aakash1419** [stripe/react-stripe-elements#508]
hii..
i am getting this error while bulding react.
./node_modules/@stripe/react-stripe-js/dist/react-stripe.umd.js
Module parse failed: Unexpected token (1555:32)
You may need an appropriate loader to handle this file type.
|               return {};
|           }
|           const { paymentRequest: _, ...rest } = options;
|           return rest;
|       };
      
this usually occurs when i try to import {Elements} from '@stripe/react-stripe-js'

i had googled it many times but unable to find an appropriate solution.
i had also taken reference from this : https://github.com/stripe/react-stripe-elements/issues/377

could anyone please help

**Comment by dweedon-stripe** [comment]
Thanks for the report. This looks related to https://github.com/stripe/react-stripe-js/issues/50. There is currently a bug where we are not correctly transpiling down ES5. Should have a fix out later today.

I am going to close this issue since it is about React Stripe.js not `react-stripe-elements`, feel free to post any additional information on the existing issue thread.
