### ISSUE TITLE
Change Stripe API Version

### ISSUE THREAD

**Issue by epintos** [stripe/react-stripe-elements#516]
Is it possible to change the Stripe API version to a specific version as suggested [here](https://stripe.com/docs/upgrades#how-can-i-upgrade-my-api) with the `Stripe-Version` header?

**Comment by epintos** [comment]
I just saw [here](https://github.com/stripe/stripe-js/blob/8570f20ec9b27807c95100a828088c82fedf3df5/types/stripe-js/index.d.ts#L368) that is possible to add it a parameter to the Stripe object. Is there another way?

**Comment by hofman-stripe** [comment]
@epintos, what other way are you looking for? As you've discovered, you can create a stripe object with a specific `apiVersion`, and [use it with `react-stripe-elements`](https://github.com/stripe/react-stripe-elements#using-an-existing-stripe-instance).

**Comment by epintos** [comment]
@hofman-stripe Yes, that is already a good solution for me, but I was also thinking about a configuration file where you add the Stripe API Version that you want. So the version is outside of the code.

**Comment by hofman-stripe** [comment]
Unless I'm not understanding something, that would have to be something that depends on the tooling and framework you use, not something this or any of our library can provide.

When not specifying an API Version, the default version configured for your account will be used. That's the only external configuration possible.

I'm going to close this issue since this is not related to these React bindings. [Stripe Support](https://support.stripe.com/) should be able to help you with any general question regarding your integration.

**Comment by maxjacobson** [comment]
Hi there!

I stumbled on this issue, because I was looking to do the same thing. Sharing this in case it's helpful to anyone else.

I had:

```jsx
<StripeProvider apiKey={apiKey}>
```

I was about to change it to:

```jsx
const stripe = Stripe(apiKey, { apiVersion: '2019-12-03' });

<StripeProvider stripe={stripe}>
```

When I looked at [the source code](https://github.com/stripe/react-stripe-elements/blob/0eeadf2815f06bb48f4f61228364465108763428/src/components/Provider.js#L100-L101), which suggests that this will work just fine, and it's a smaller diff, which I like:


```jsx
<StripeProvider apiKey={apiKey} apiVersion={'2019-12-03'}>
```

If I'm right that this is a supported way to use the library, I think it would make sense to include an example about this in the docs.
