### ISSUE TITLE
Original Component not available after wrapped in injectStripe

### ISSUE THREAD

**Issue by sciku1** [stripe/react-stripe-elements#72]
Essentially, when trying to reference a component that is wrapped by the the injectStripe HOC, I can't access any of it's. I created a codepen to illustrate the problem:

https://codepen.io/sciku1/pen/oemNEg

Is there any way to get around this? Thanks.

**Comment by cweiss-stripe** [comment]
Thanks for the suggestion. This does currently not seem to be possible.
Can you elaborate a little on the use case why you need to be able to do this?

We can look into creating an option like `injectStripe(CardForm, {withRef: true});`
and then making the wrapped instance available via `this.refs.cardForm.getWrappedInstance()`.

This should probably not be the default, because it might not work with stateless functional components.

I'll look into this!

**Comment by cweiss-stripe** [comment]
This functionality was added in #75.
I'll create a new release soon.

**Comment by sciku1** [comment]
Awesome thanks! Use case was that I wanted to have the card component be able to create a token,  which could then be submitted as part of the form. I did find a work around, but thank you for adding the feature! Will definitely use the library again in the future :+1:

**Comment by Emixam23** [comment]
Hey, I am not sure to understand the answers :/

So the idea is to not use inject stripe with default?
