### ISSUE TITLE
Add support for a redux-stored `stripe` instance.

### ISSUE THREAD

**Issue by michelle-stripe** [stripe/react-stripe-elements#8]
Perhaps something like:

```jsx
<Elements stripe={this.props.stripeInstance}>
   <MyCheckoutForm />
</Elements>
```

**Comment by michael-reeves** [comment]
This would be really nice to have.

I asked these questions of Michelle directly, but I'll put them in here for everyone to see.

Qs:
Would this be some kind of middleware layer that adds the instance to the store?  If not, how would you get the instance into the redux-store to begin with?  I started using react-stripe-elements because I was unable to figure out how to access the "Stripe" object from within my components directly.  Some detailed docs would probably be useful.  

Would the stripeInstance be accessible on state, or just inside the action creator?  Usually my state would look something like this.state.stripe.sourceToken, or maybe this.state.stripe.errors.  Maybe something like this.state.stripe.card.token (or errors) be better, considering all the things stripe can handle?  In general, I don't know that you want the stripe instance available externally on state.  Seems like something you could screw up later if you're not careful, but I'm definitely not an expert.

What would need to be passed to an action creator to use createToken?  So far in the example, this.props.stripe seems to contain a reference to the correct Element.  But inside the "CheckoutForm" in my setup, I’m using multiple <*Element> items on my form.  Is there a list of all the *Elements on the form that should be passed?  It seems like <Elements> may already know about all the *Element(s) that exist on the form, so maybe there’s something else that would work.  The way this is implemented in Stripe.js and react-stripe-elements seems a bit hidden/magical.  Perhaps it just needs a reference to CardNumberElement and the rest will get worked out automatically.

I'm wasn't planning to use the form to process a purchase directly, but to create a token, then attach it to a user's account, so I will presumably have multiple calls from the stripe instance in my action creator before my form modal closes.  Not sure if that is important to this discussion or not, but it might impact things.
