### ISSUE TITLE
Consider introducing CHANGELOG.md

### ISSUE THREAD

**Issue by puradox** [stripe/react-stripe-elements#88]
I know that there is a releases page, but it would be nice if there were a changelog file in the project directory breaking changes between releases. 

Possible options include using [`standard-option`](https://github.com/conventional-changelog/standard-version) for automatic changelog generation.

**Comment by jez-stripe** [comment]
Oh, this sounds like a good idea! I think for now we'll just keep changes at the "releases" page because we don't make very frequent changes, especially now that we've hit version 1.0.

That being said, communicating new features in Stripe.js and `react-stripe-elements` is a broader goal that we're working on. Thanks for the tip!

**Comment by eideer** [comment]
This would be useful, the latest v2.0.2 tag in releases has no description, and the diff is a little confusing/surprising..

https://github.com/stripe/react-stripe-elements/releases/tag/v2.0.2
https://github.com/stripe/react-stripe-elements/compare/v2.0.1...v2.0.2
